# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'LidcAnalyzerView.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_LidcAnalyzer(object):
    def setupUi(self, LidcAnalyzer):
        LidcAnalyzer.setObjectName("LidcAnalyzer")
        LidcAnalyzer.resize(933, 641)
        self.gridLayout = QtWidgets.QGridLayout(LidcAnalyzer)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox_2 = QtWidgets.QGroupBox(LidcAnalyzer)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.groupBox_2)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.gridLayout_2.addWidget(self.plainTextEdit, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox_2, 2, 8, 5, 1)
        self.groupBox = QtWidgets.QGroupBox(LidcAnalyzer)
        self.groupBox.setMaximumSize(QtCore.QSize(16777215, 265))
        self.groupBox.setObjectName("groupBox")
        self.formLayout = QtWidgets.QFormLayout(self.groupBox)
        self.formLayout.setObjectName("formLayout")
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.lineEdit_Subtlety = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_Subtlety.setReadOnly(True)
        self.lineEdit_Subtlety.setObjectName("lineEdit_Subtlety")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit_Subtlety)
        self.label_ = QtWidgets.QLabel(self.groupBox)
        self.label_.setObjectName("label_")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_)
        self.lineEdit_InternalStructure = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_InternalStructure.setReadOnly(True)
        self.lineEdit_InternalStructure.setObjectName("lineEdit_InternalStructure")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_InternalStructure)
        self.label_9 = QtWidgets.QLabel(self.groupBox)
        self.label_9.setObjectName("label_9")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.lineEdit_Calcification = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_Calcification.setReadOnly(True)
        self.lineEdit_Calcification.setObjectName("lineEdit_Calcification")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEdit_Calcification)
        self.label_10 = QtWidgets.QLabel(self.groupBox)
        self.label_10.setObjectName("label_10")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.lineEdit_Sphericity = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_Sphericity.setReadOnly(True)
        self.lineEdit_Sphericity.setObjectName("lineEdit_Sphericity")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.lineEdit_Sphericity)
        self.label_11 = QtWidgets.QLabel(self.groupBox)
        self.label_11.setObjectName("label_11")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.lineEdit_Margin = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_Margin.setReadOnly(True)
        self.lineEdit_Margin.setObjectName("lineEdit_Margin")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.lineEdit_Margin)
        self.label_13 = QtWidgets.QLabel(self.groupBox)
        self.label_13.setObjectName("label_13")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_13)
        self.lineEdit_Lobulation = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_Lobulation.setReadOnly(True)
        self.lineEdit_Lobulation.setObjectName("lineEdit_Lobulation")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.lineEdit_Lobulation)
        self.label_14 = QtWidgets.QLabel(self.groupBox)
        self.label_14.setObjectName("label_14")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_14)
        self.lineEdit_Spiculation = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_Spiculation.setReadOnly(True)
        self.lineEdit_Spiculation.setObjectName("lineEdit_Spiculation")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.lineEdit_Spiculation)
        self.label_Texture = QtWidgets.QLabel(self.groupBox)
        self.label_Texture.setObjectName("label_Texture")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_Texture)
        self.lineEdit_Texture = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_Texture.setReadOnly(True)
        self.lineEdit_Texture.setObjectName("lineEdit_Texture")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.lineEdit_Texture)
        self.label_16 = QtWidgets.QLabel(self.groupBox)
        self.label_16.setObjectName("label_16")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.label_16)
        self.lineEdit_Malignancy = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_Malignancy.setReadOnly(True)
        self.lineEdit_Malignancy.setObjectName("lineEdit_Malignancy")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.lineEdit_Malignancy)
        self.label_12 = QtWidgets.QLabel(self.groupBox)
        self.label_12.setGeometry(QtCore.QRect(10, 230, 111, 16))
        self.label_12.setText("")
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.groupBox, 0, 8, 2, 1)
        self.lineEdit_SeriesID = QtWidgets.QLineEdit(LidcAnalyzer)
        self.lineEdit_SeriesID.setReadOnly(True)
        self.lineEdit_SeriesID.setObjectName("lineEdit_SeriesID")
        self.gridLayout.addWidget(self.lineEdit_SeriesID, 5, 1, 1, 4)
        self.pushButton_OpenLidc = QtWidgets.QPushButton(LidcAnalyzer)
        self.pushButton_OpenLidc.setObjectName("pushButton_OpenLidc")
        self.gridLayout.addWidget(self.pushButton_OpenLidc, 0, 0, 1, 2)
        self.label_6 = QtWidgets.QLabel(LidcAnalyzer)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 6, 3, 1, 1)
        self.lineEdit_StudyID = QtWidgets.QLineEdit(LidcAnalyzer)
        self.lineEdit_StudyID.setReadOnly(True)
        self.lineEdit_StudyID.setObjectName("lineEdit_StudyID")
        self.gridLayout.addWidget(self.lineEdit_StudyID, 4, 1, 1, 4)
        self.label_3 = QtWidgets.QLabel(LidcAnalyzer)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 3, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(LidcAnalyzer)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 4, 0, 1, 1)
        self.lineEdit_NoduleCount = QtWidgets.QLineEdit(LidcAnalyzer)
        self.lineEdit_NoduleCount.setReadOnly(True)
        self.lineEdit_NoduleCount.setObjectName("lineEdit_NoduleCount")
        self.gridLayout.addWidget(self.lineEdit_NoduleCount, 6, 1, 1, 2)
        self.label_2 = QtWidgets.QLabel(LidcAnalyzer)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 5, 0, 1, 1)
        self.lineEdit_PatientID = QtWidgets.QLineEdit(LidcAnalyzer)
        self.lineEdit_PatientID.setReadOnly(True)
        self.lineEdit_PatientID.setObjectName("lineEdit_PatientID")
        self.gridLayout.addWidget(self.lineEdit_PatientID, 3, 1, 1, 4)
        self.lineEdit_nonNoduleCount = QtWidgets.QLineEdit(LidcAnalyzer)
        self.lineEdit_nonNoduleCount.setReadOnly(True)
        self.lineEdit_nonNoduleCount.setObjectName("lineEdit_nonNoduleCount")
        self.gridLayout.addWidget(self.lineEdit_nonNoduleCount, 6, 4, 1, 1)
        self.lineEdit_LidcRootDir = QtWidgets.QLineEdit(LidcAnalyzer)
        self.lineEdit_LidcRootDir.setObjectName("lineEdit_LidcRootDir")
        self.gridLayout.addWidget(self.lineEdit_LidcRootDir, 0, 2, 1, 4)
        self.label_5 = QtWidgets.QLabel(LidcAnalyzer)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 6, 0, 1, 1)
        self.pushButton_ShowROI = QtWidgets.QPushButton(LidcAnalyzer)
        self.pushButton_ShowROI.setObjectName("pushButton_ShowROI")
        self.gridLayout.addWidget(self.pushButton_ShowROI, 3, 5, 1, 1)
        self.pushButton_ShowLung = QtWidgets.QPushButton(LidcAnalyzer)
        self.pushButton_ShowLung.setObjectName("pushButton_ShowLung")
        self.gridLayout.addWidget(self.pushButton_ShowLung, 4, 5, 1, 1)
        self.gridLayout_ForImg = QtWidgets.QGridLayout()
        self.gridLayout_ForImg.setObjectName("gridLayout_ForImg")
        self.gridLayout.addLayout(self.gridLayout_ForImg, 1, 0, 2, 7)
        self.pushButton_FrontSeries = QtWidgets.QPushButton(LidcAnalyzer)
        self.pushButton_FrontSeries.setObjectName("pushButton_FrontSeries")
        self.gridLayout.addWidget(self.pushButton_FrontSeries, 6, 5, 1, 1)
        self.verticalScrollBar = QtWidgets.QScrollBar(LidcAnalyzer)
        self.verticalScrollBar.setOrientation(QtCore.Qt.Vertical)
        self.verticalScrollBar.setObjectName("verticalScrollBar")
        self.gridLayout.addWidget(self.verticalScrollBar, 1, 7, 2, 1)
        self.pushButton_ShowLocus = QtWidgets.QPushButton(LidcAnalyzer)
        self.pushButton_ShowLocus.setObjectName("pushButton_ShowLocus")
        self.gridLayout.addWidget(self.pushButton_ShowLocus, 3, 6, 1, 2)
        self.pushButton_ShowLabel = QtWidgets.QPushButton(LidcAnalyzer)
        self.pushButton_ShowLabel.setObjectName("pushButton_ShowLabel")
        self.gridLayout.addWidget(self.pushButton_ShowLabel, 4, 6, 1, 2)
        self.pushButton_ExportLabels = QtWidgets.QPushButton(LidcAnalyzer)
        self.pushButton_ExportLabels.setObjectName("pushButton_ExportLabels")
        self.gridLayout.addWidget(self.pushButton_ExportLabels, 5, 5, 1, 3)
        self.pushButton_BackSeries = QtWidgets.QPushButton(LidcAnalyzer)
        self.pushButton_BackSeries.setObjectName("pushButton_BackSeries")
        self.gridLayout.addWidget(self.pushButton_BackSeries, 6, 6, 1, 2)
        self.pushButton_StartAnalyze = QtWidgets.QPushButton(LidcAnalyzer)
        self.pushButton_StartAnalyze.setObjectName("pushButton_StartAnalyze")
        self.gridLayout.addWidget(self.pushButton_StartAnalyze, 0, 6, 1, 2)

        self.retranslateUi(LidcAnalyzer)
        QtCore.QMetaObject.connectSlotsByName(LidcAnalyzer)

    def retranslateUi(self, LidcAnalyzer):
        _translate = QtCore.QCoreApplication.translate
        LidcAnalyzer.setWindowTitle(_translate("LidcAnalyzer", "Lidc Analyzer"))
        self.groupBox_2.setTitle(_translate("LidcAnalyzer", "OutPut"))
        self.groupBox.setTitle(_translate("LidcAnalyzer", "Characteristics"))
        self.label_7.setText(_translate("LidcAnalyzer", "subtlety:"))
        self.label_.setText(_translate("LidcAnalyzer", "internal Structure:"))
        self.label_9.setText(_translate("LidcAnalyzer", "calcification:"))
        self.label_10.setText(_translate("LidcAnalyzer", "sphericity:"))
        self.label_11.setText(_translate("LidcAnalyzer", "margin:"))
        self.label_13.setText(_translate("LidcAnalyzer", "lobulation:"))
        self.label_14.setText(_translate("LidcAnalyzer", "spiculation:"))
        self.label_Texture.setText(_translate("LidcAnalyzer", "texture:"))
        self.label_16.setText(_translate("LidcAnalyzer", "malignancy:"))
        self.pushButton_OpenLidc.setText(_translate("LidcAnalyzer", "打开LIDC-IDRI文件夹"))
        self.label_6.setText(_translate("LidcAnalyzer", "uonNodule Count:"))
        self.label_3.setText(_translate("LidcAnalyzer", "Parient ID:"))
        self.label_4.setText(_translate("LidcAnalyzer", "Study ID:"))
        self.label_2.setText(_translate("LidcAnalyzer", "Series ID:"))
        self.label_5.setText(_translate("LidcAnalyzer", "Nodule Count:"))
        self.pushButton_ShowROI.setText(_translate("LidcAnalyzer", "显示ROI"))
        self.pushButton_ShowLung.setText(_translate("LidcAnalyzer", "启动肺实质分割"))
        self.pushButton_FrontSeries.setText(_translate("LidcAnalyzer", "前一个序列"))
        self.pushButton_ShowLocus.setText(_translate("LidcAnalyzer", "显示locus"))
        self.pushButton_ShowLabel.setText(_translate("LidcAnalyzer", "生成标注图"))
        self.pushButton_ExportLabels.setText(_translate("LidcAnalyzer", "导出当前序列的全部标注图"))
        self.pushButton_BackSeries.setText(_translate("LidcAnalyzer", "后一个序列"))
        self.pushButton_StartAnalyze.setText(_translate("LidcAnalyzer", "开始分析"))

