# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'LidcAnalyzerView.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_LidcAnalyzer(object):
    def setupUi(self, LidcAnalyzer):
        LidcAnalyzer.setObjectName("LidcAnalyzer")
        LidcAnalyzer.resize(862, 625)
        self.gridLayout_2 = QtWidgets.QGridLayout(LidcAnalyzer)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.pushButton_OpenLidc = QtWidgets.QPushButton(LidcAnalyzer)
        self.pushButton_OpenLidc.setObjectName("pushButton_OpenLidc")
        self.gridLayout_2.addWidget(self.pushButton_OpenLidc, 0, 0, 1, 1)
        self.lineEdit_LidcRootDir = QtWidgets.QLineEdit(LidcAnalyzer)
        self.lineEdit_LidcRootDir.setObjectName("lineEdit_LidcRootDir")
        self.gridLayout_2.addWidget(self.lineEdit_LidcRootDir, 0, 1, 1, 1)
        self.pushButton_StartAnalyze = QtWidgets.QPushButton(LidcAnalyzer)
        self.pushButton_StartAnalyze.setObjectName("pushButton_StartAnalyze")
        self.gridLayout_2.addWidget(self.pushButton_StartAnalyze, 0, 2, 1, 1)
        self.splitter_2 = QtWidgets.QSplitter(LidcAnalyzer)
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName("splitter_2")
        self.tableView = QtWidgets.QTableView(self.splitter_2)
        self.tableView.setMinimumSize(QtCore.QSize(390, 150))
        self.tableView.setMaximumSize(QtCore.QSize(16777215, 180))
        self.tableView.setObjectName("tableView")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.splitter_2)
        self.plainTextEdit.setMinimumSize(QtCore.QSize(0, 0))
        self.plainTextEdit.setMaximumSize(QtCore.QSize(16777215, 240))
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.gridLayout_2.addWidget(self.splitter_2, 3, 0, 1, 2)
        self.label_3 = QtWidgets.QLabel(LidcAnalyzer)
        self.label_3.setMaximumSize(QtCore.QSize(80, 16777215))
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 4, 0, 1, 1)
        self.lineEdit_PatientID = QtWidgets.QLineEdit(LidcAnalyzer)
        self.lineEdit_PatientID.setReadOnly(True)
        self.lineEdit_PatientID.setObjectName("lineEdit_PatientID")
        self.gridLayout_2.addWidget(self.lineEdit_PatientID, 4, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(LidcAnalyzer)
        self.label_4.setMaximumSize(QtCore.QSize(80, 16777215))
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 5, 0, 1, 1)
        self.lineEdit_StudyID = QtWidgets.QLineEdit(LidcAnalyzer)
        self.lineEdit_StudyID.setReadOnly(True)
        self.lineEdit_StudyID.setObjectName("lineEdit_StudyID")
        self.gridLayout_2.addWidget(self.lineEdit_StudyID, 5, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(LidcAnalyzer)
        self.label_2.setMaximumSize(QtCore.QSize(80, 16777215))
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 6, 0, 1, 1)
        self.lineEdit_SeriesID = QtWidgets.QLineEdit(LidcAnalyzer)
        self.lineEdit_SeriesID.setReadOnly(True)
        self.lineEdit_SeriesID.setObjectName("lineEdit_SeriesID")
        self.gridLayout_2.addWidget(self.lineEdit_SeriesID, 6, 1, 1, 1)
        self.SliceScrollBar = QtWidgets.QScrollBar(LidcAnalyzer)
        self.SliceScrollBar.setOrientation(QtCore.Qt.Horizontal)
        self.SliceScrollBar.setObjectName("SliceScrollBar")
        self.gridLayout_2.addWidget(self.SliceScrollBar, 2, 0, 1, 3)
        self.splitter = QtWidgets.QSplitter(LidcAnalyzer)
        self.splitter.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.layoutWidget = QtWidgets.QWidget(self.splitter)
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout_ForImg = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout_ForImg.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.gridLayout_ForImg.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_ForImg.setObjectName("gridLayout_ForImg")
        self.layoutWidget1 = QtWidgets.QWidget(self.splitter)
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.gridLayout_ForMask = QtWidgets.QGridLayout(self.layoutWidget1)
        self.gridLayout_ForMask.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_ForMask.setObjectName("gridLayout_ForMask")
        self.gridLayout_2.addWidget(self.splitter, 1, 0, 1, 3)
        self.groupBox = QtWidgets.QGroupBox(LidcAnalyzer)
        self.groupBox.setMaximumSize(QtCore.QSize(200, 16777215))
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_FrontSeries = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_FrontSeries.setObjectName("pushButton_FrontSeries")
        self.gridLayout.addWidget(self.pushButton_FrontSeries, 6, 0, 1, 1)
        self.pushButton_ShowROI = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_ShowROI.setObjectName("pushButton_ShowROI")
        self.gridLayout.addWidget(self.pushButton_ShowROI, 1, 0, 1, 1)
        self.pushButton_ShowLabel = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_ShowLabel.setObjectName("pushButton_ShowLabel")
        self.gridLayout.addWidget(self.pushButton_ShowLabel, 5, 0, 1, 1)
        self.pushButton_ShowLocus = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_ShowLocus.setObjectName("pushButton_ShowLocus")
        self.gridLayout.addWidget(self.pushButton_ShowLocus, 2, 0, 1, 1)
        self.pushButton_ExportLabels = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_ExportLabels.setObjectName("pushButton_ExportLabels")
        self.gridLayout.addWidget(self.pushButton_ExportLabels, 0, 0, 1, 3)
        self.pushButton_BackSeries = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_BackSeries.setObjectName("pushButton_BackSeries")
        self.gridLayout.addWidget(self.pushButton_BackSeries, 7, 0, 1, 1)
        self.pushButton_ShowLung = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_ShowLung.setObjectName("pushButton_ShowLung")
        self.gridLayout.addWidget(self.pushButton_ShowLung, 4, 0, 1, 2)
        self.gridLayout_2.addWidget(self.groupBox, 3, 2, 4, 1)

        self.retranslateUi(LidcAnalyzer)
        QtCore.QMetaObject.connectSlotsByName(LidcAnalyzer)

    def retranslateUi(self, LidcAnalyzer):
        _translate = QtCore.QCoreApplication.translate
        LidcAnalyzer.setWindowTitle(_translate("LidcAnalyzer", "Lidc Analyzer"))
        self.pushButton_OpenLidc.setText(_translate("LidcAnalyzer", "打开LIDC-IDRI文件夹"))
        self.pushButton_StartAnalyze.setText(_translate("LidcAnalyzer", "开始分析"))
        self.label_3.setText(_translate("LidcAnalyzer", "Parient ID:"))
        self.label_4.setText(_translate("LidcAnalyzer", "Study ID:"))
        self.label_2.setText(_translate("LidcAnalyzer", "Series ID:"))
        self.groupBox.setTitle(_translate("LidcAnalyzer", "Functions"))
        self.pushButton_FrontSeries.setText(_translate("LidcAnalyzer", "前一个序列"))
        self.pushButton_ShowROI.setText(_translate("LidcAnalyzer", "显示ROI"))
        self.pushButton_ShowLabel.setText(_translate("LidcAnalyzer", "生成标注图"))
        self.pushButton_ShowLocus.setText(_translate("LidcAnalyzer", "显示locus"))
        self.pushButton_ExportLabels.setText(_translate("LidcAnalyzer", "导出当前序列的全部标注图"))
        self.pushButton_BackSeries.setText(_translate("LidcAnalyzer", "后一个序列"))
        self.pushButton_ShowLung.setText(_translate("LidcAnalyzer", "启动肺实质分割"))

